package compas.common;

/**
 * Created by Ceasar on 06/05/2019.
 */
public class MiddlewareRequestActions {

	public static final String MIDDLEWARE_REQ_ACTION_TRANSFER_DR_CR = "TRANSFER";
	public static final String MIDDLEWARE_REQ_ACTION_ACCT_INQUIRY = "ACCT_INQUIRY";
	public static final String MIDDLEWARE_REQ_ACTION_BAL = "BAL";
	public static final String MIDDLEWARE_REQ_ACTION_MINI = "MINI";
	public static final String MIDDLEWARE_REQ_ACTION_DEPOSIT = "DEPOSIT";
	public static final String MIDDLEWARE_REQ_ACTION_WITHDRAW = "WITHDRAW";
	public static final String MIDDLEWARE_REQ_ACTION_TRANSFER_INTRA = "TRANSFER_INTRA";
	public static final String MIDDLEWARE_REQ_ACTION_TRANSFER_INTER = "TRANSFER_INTER";
	public static final String MIDDLEWARE_REQ_ACTION_FULL = "FULL";
	//
	public static final String MIDDLEWARE_REQ_ACTION_PAYBILL_UMEME_VALIDATE = "PAYBILL_UMEME_VALIDATE";
	public static final String MIDDLEWARE_REQ_ACTION_PAYBILL_UMEME_PAYMENT = "PAYBILL_UMEME_PAYMENT";
	//NWSC
	public static final String MIDDLEWARE_REQ_ACTION_NWSC_SELECT_AREA_OF_RESIDENCE = "PAYBILL_NWSC_AREAS";
	public static final String MIDDLEWARE_REQ_ACTION_NWSC_VALIDATE_CUSTOMER = "PAYBILL_NWSC_VALIDATE";
	public static final String MIDDLEWARE_REQ_ACTION_NWSC_PAYMENT_BILL_FULLFILMENT = "PAYBILL_NWSC_PAYMENT";
	//School fees
	public static final String MIDDLEWARE_REQ_ACTION_SCHOOLPAY_VALIDATE = "SCHOOLPAY_VALIDATE";
	public static final String MIDDLEWARE_REQ_ACTION_SCHOOLPAY_PAYMENT_BILL_FULLFILMENT = "SCHOOLPAY_PAYMENT";
	//DSTV
	public static final String MIDDLEWARE_REQ_ACTION_DSTV_VALIDATE = "PAYBILL_DSTV_VALIDATE";
	public static final String MIDDLEWARE_REQ_ACTION_PAYBILL_DSTV_PAYMENT_BILL_FULLFILMENT = "PAYBILL_DSTV_PAYMENT";
	//GOTV
	public static final String MIDDLEWARE_REQ_ACTION_PAYBILL_GOTV_VALIDATE = "PAYBILL_GOTV_VALIDATE";
	public static final String MIDDLEWARE_REQ_ACTION_PAYBILL_GOTV_PAYMENT_BILL_FULLFILMENT = "PAYBILL_GOTV_PAYMENT";
	
	public static final String MIDDLEWARE_REQ_ACTION_CARD_APPLICATION = "CARD_APPLICATION";
	public static final String MIDDLEWARE_REQ_ACTION_LOAN_APPLICATION = "LOAN_APPLICATION";

	


	

	

}
